apiVersion: v1
kind: Service
metadata:
  name: flaky-svc-126332246
  namespace: probes-126332246
spec:
  selector:
    app: flaky-126332246
  ports:
    - name: http
      port: 80
      targetPort: 8080
    type: ClusterIP