apiVersion: v1
kind: Pod
metadata:
  name: curl-client
  namespace: probes-126332246
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "infinity"]
  restartPolicy: Always